#!/bin/bash
UninstallThis() {
  InPackageName=$1
  InAppName=$2
  echo -e -n '  — \E[35;01;03m'$InPackageName'\E[34;01;03m '$InAppName'\E[0m : '
  for CurPackage in "${PackagesList[@]}"; do
    if [[ $CurPackage == $InPackageName ]]; then
      echo -e '\E[31;01m✘\E[0m '"found: uninstall"
      adb shell pm uninstall --user 0 $InPackageName
      return 0
    fi
  done
  echo -e '\E[32;01m✔\E[0m '"not found"
  return 1
}

#***********************
#* Programme principal *
#***********************
#uninstall non system packages
PackagesList=( $(adb shell pm list packages | awk -F':' '{print $2}' | sed 's/\r$//') )

#uninstall system packages
PackagesList=( $(adb shell pm list packages -s | awk -F':' '{print $2}' | sed 's/\r$//') )
UninstallThis "com.android.quicksearchbox" "Android search bar"
UninstallThis "com.android.fmradio" "FM radio"
UninstallThis "com.android.music" "android basic music app"
UninstallThis "com.android.musicfx" "androdi basic music app"
UninstallThis "com.android.soundrecorder" "android basic sound recorder"
UninstallThis "com.android.calculator" "android calculator"
UninstallThis "com.android.calculator2" "android calculator 2"
#UninstallThis "com.android.deskclock" "android desktop clock"
UninstallThis "com.android.protips" "tips for welcome screen"
UninstallThis "com.android.chrome" "Chrome Browser"
UninstallThis "com.android.browser" "Basic Browser"
UninstallThis "com.android.email" "Email basic app"
#UninstallThis "com.android.vending" "Play store"

# dangerous to remove thes apps
#UninstallThis "com.android.documentsui" "android base file browse app"
#UninstallThis "com.android.camera" "android base camera app"
#UninstallThis "com.android.camera2" "android base camera app"

#UninstallThis "com.android.dialer" "android base dialer app"
#UninstallThis "com.android.contacts" "android base contacts app"
#UninstallThis "com.android.calendar" "android base calendar app"
#UninstallThis "com.android.phone" "android base phone app" #do not remove this app!!!

#to reinstall base app:
# adb shell cmd package install-existing com.android.phone

echo "Done!"

