#!/bin/bash
UninstallThis() {
  InPackageName=$1
  InAppName=$2
  echo -e -n '  — \E[35;01;03m'$InPackageName'\E[34;01;03m '$InAppName'\E[0m : '
  for CurPackage in "${PackagesList[@]}"; do
    if [[ $CurPackage == $InPackageName ]]; then
      echo -e '\E[31;01m✘\E[0m '"found: uninstall"
      adb shell pm uninstall --user 0 $InPackageName
      return 0
    fi
  done
  echo -e '\E[32;01m✔\E[0m '"not found"
  return 1
}

#***********************
#* Programme principal *
#***********************
#uninstall system packages
PackagesList=( $(adb shell pm list packages -s | awk -F':' '{print $2}' | sed 's/\r$//') )

UninstallThis "com.google.android.googlequicksearchbox" "Google Search Bar On Home Page"
UninstallThis "com.google.android.keep" "Notes Keep"
UninstallThis "com.google.android.talk" "Google talk"
UninstallThis "com.google.android.youtube" "Youtube"
UninstallThis "com.google.android.videos" "Google films et séries"
UninstallThis "com.google.android.music" "Google music"
UninstallThis "com.google.android.feedback"
UninstallThis "com.google.android.tts" "Google speech recognition & synthesis"
UninstallThis "com.google.android.marvin.talkback" "Talkback feature"
UninstallThis "com.google.android.apps.tachyon" "Google Duo"
#UninstallThis "com.google.android.gm" "Gmail"
#UninstallThis "com.google.android.gms" "Gmail service: needed for Google play!"
UninstallThis "com.google.android.gms.location.history" "Google Play Tracking Location"
UninstallThis "com.google.android.apps.docs" "Google Drive"
UninstallThis "com.google.android.apps.youtube.music" "Youtube Music"
UninstallThis "com.google.android.apps.maps" "Google Maps"
UninstallThis "com.google.android.apps.plus"
UninstallThis "com.google.android.apps.books"
UninstallThis "com.google.android.apps.magazines"
UninstallThis "com.google.android.apps.photos"
UninstallThis "com.google.android.apps.cloudprint"
UninstallThis "com.google.android.apps.googleassistant" "Google Assistant"
UninstallThis "com.google.android.apps.subscriptions.red" "Google One"
UninstallThis "com.google.android.apps.fitness" "Google Fit"
UninstallThis "com.google.android.apps.nbu.files" "Files by Google"
UninstallThis "com.google.android.apps.adm" "Google find my device"
UninstallThis "com.google.android.apps.bard" "Google Gemini"

#UninstallThis "com.google.android.dialer" "Google dialer app"
#UninstallThis "com.google.android.contacts" "Google contacts app"
#UninstallThis "com.google.android.calendar" "Google calendar app"
UninstallThis "com.google.android.syncadapters.calendar" "Google calendar online sync"
UninstallThis "com.google.android.syncadapters.contacts" "Google contacts app"

UninstallThis "com.google.android.apps.messaging" "Google message app"
UninstallThis "com.google.android.documentsui" "Google file browse app"

#uninstall non system packages
#PackagesList=( $(adb shell pm list packages | awk -F':' '{print $2}' | sed 's/\r$//') )

echo "Done!"

