#!/bin/bash
UninstallThis() {
  InPackageName=$1
  InAppName=$2
  echo -e -n '  — \E[35;01;03m'$InPackageName'\E[34;01;03m '$InAppName'\E[0m : '
  for CurPackage in "${PackagesList[@]}"; do
    if [[ $CurPackage == $InPackageName ]]; then
      echo -e '\E[31;01m✘\E[0m '"found: uninstall"
      adb shell pm uninstall --user 0 $InPackageName
      return 0
    fi
  done
  echo -e '\E[32;01m✔\E[0m '"not found"
  return 1
}

#***********************
#* Programme principal *
#***********************
#uninstall non system packages
PackagesList=( $(adb shell pm list packages | awk -F':' '{print $2}' | sed 's/\r$//') )
UninstallThis "com.blackview.weather" "Blackview meteo"
UninstallThis "com.google.android.apps.nbu.files" "Files by Google"

#uninstall system packages
PackagesList=( $(adb shell pm list packages -s | awk -F':' '{print $2}' | sed 's/\r$//') )
# android base apps
UninstallThis "com.android.fmradio" "FM radio"

# google base apps
UninstallThis "com.google.android.googlequicksearchbox" "Google Search Bar On Home Page"
UninstallThis "com.google.android.youtube" "Youtube"
UninstallThis "com.google.android.videos" "Google films et séries"
UninstallThis "com.google.android.feedback"
UninstallThis "com.google.android.marvin.talkback" "Talkback feature"
UninstallThis "com.google.android.apps.tachyon" "Google Duo"
UninstallThis "com.google.android.gm" "Gmail"
UninstallThis "com.google.android.apps.docs" "Google Drive"
UninstallThis "com.google.android.apps.photos" "Google Photo"
UninstallThis "com.google.android.syncadapters.calendar" "Google calendar online sync"
UninstallThis "com.google.android.syncadapters.contacts" "Google contacts app"

echo "Done!"

