#!/bin/bash
UninstallThis() {
  InPackageName=$1
  InAppName=$2
  echo -e -n '  — \E[35;01;03m'$InPackageName'\E[34;01;03m '$InAppName'\E[0m : '
  for CurPackage in "${PackagesList[@]}"; do
    if [[ $CurPackage == $InPackageName ]]; then
      echo -e '\E[31;01m✘\E[0m '"found: uninstall"
      adb shell pm uninstall --user 0 $InPackageName
      return 0
    fi
  done
  echo -e '\E[32;01m✔\E[0m '"not found"
  return 1
}

#***********************
#* Programme principal *
#***********************
#uninstall non system packages
PackagesList=( $(adb shell pm list packages | awk -F':' '{print $2}' | sed 's/\r$//') )
UninstallThis "com.google.android.apps.fitness" "Google Fit"
UninstallThis "com.google.android.apps.nbu.files" "Files by Google"
UninstallThis "cn.wps.moffice_eng" "WPS office"
UninstallThis "com.blackview.weather" "Blackview meteo"

#uninstall system packages
PackagesList=( $(adb shell pm list packages -s | awk -F':' '{print $2}' | sed 's/\r$//') )
# basic android apps
UninstallThis "com.android.fmradio" "FM radio"
#UninstallThis "com.android.contacts" "android base contacts app"
UninstallThis "com.android.chrome" "Google Chrome Browser"

# google apps
UninstallThis "com.google.android.googlequicksearchbox" "Google Search Bar On Home Page"
UninstallThis "com.google.android.youtube" "Youtube"
UninstallThis "com.google.android.videos" "Google films et séries"
UninstallThis "com.google.android.feedback"
UninstallThis "com.google.android.marvin.talkback" "Talkback feature"
UninstallThis "com.google.android.apps.tachyon" "Google Duo"
UninstallThis "com.google.android.gm" "Gmail"
UninstallThis "com.google.android.apps.docs" "Google Drive"
UninstallThis "com.google.android.apps.photos" "Google photo"
UninstallThis "com.google.android.calendar" "Google agenda"
UninstallThis "com.google.android.projection.gearhead" "Android Auto"
#UninstallThis "com.google.android.dialer" "Google dialer app"
#UninstallThis "com.google.android.contacts" "Google contacts app"
#UninstallThis "com.google.android.documentsui" "Google file browse app" # you should not uninstall this one
UninstallThis "com.google.android.healthconnect.controller" "Santé connect"
UninstallThis "com.google.android.apps.youtube.music" "Youtube Music"
UninstallThis "com.google.android.keep" "Notes Keep"
UninstallThis "com.google.android.apps.bard" "Google Gemini"
UninstallThis "com.google.android.apps.maps" "Google Maps"
UninstallThis "com.google.android.apps.adm" "Google find my device"
UninstallThis "com.google.android.gms.supervision" "Système de controle parental"

# Blackview system apps
UninstallThis "com.blackview.easytrans" "Blakview easy share"
UninstallThis "com.blackview.bvworkspace" "Blakview espace de travail"
UninstallThis "com.blackview.ai.doki" "Hi Doki"
UninstallThis "com.blackview.ai.imagex" "ImageX"
UninstallThis "com.blackview.ai.soundle" "Soundle"
UninstallThis "com.blackview.ai.vidgen" "Vidgen"
UninstallThis "com.blackview.childmode" "Mode enfant"
UninstallThis "com.blackview.health" "Santé"

echo "Done!"

